### ISSUE TITLE
Suggestion: Seperate regular register hide from regular login hide

### ISSUE THREAD

**Issue by amint** [alixandru/q2a-open-login#45]
Say the Admin, for example, has last loggedin using his regular email account and now he has hidden the regular login , and for same reason he cannot log in via yourDomain.com/login, what is he supposed to do now?
IMO, would work better to give two separate options to the admin
1- Disable regular register
2- hide regular login

-This way if the admin only checks no1, then the users who already registered via regular login can continue to login, but new users have to register via social logins.

No2 only hides the login text boxes from front page, therefor the admin can still login via yourDomain.com/login.
So If the admin selects both 1 and 2, he can still be fine. 
(if you argue same way regular users can login in too, i would say only the ones already logged in and dont want ofcourse to be kicked out after we use your plugin)
Also:
Say at the begging of the launch of website the only user is admin, he select both, this way no new regular user will register, let alone logs in.

**Comment by alixandru** [comment]
This customization can be easily made by site admins if they need it. It is not going to be implemented in the plugin.
