### ISSUE TITLE
Please update to latest hybridauth

### ISSUE THREAD

**Issue by fulldecent** [alixandru/q2a-open-login#56]
I would submit a pull request for this but I cannot get even the current version of q2a-open-login to work, so I don't want to be responsible for breaking it for everyone else :-)

Specifically, my current problem is that I can login to an existing account but I cannot create a new account with q2a-open-login. However, when updating to a new version of hybridauth I am not even able to login with my existing account.

**Comment by fulldecent** [comment]
I have found that the version of hybridauth in q2a-open-login is most closely related to their commit:

https://github.com/hybridauth/hybridauth/commit/0a8cab69dae1a822a410fac3737896cf7379be6d

Although it is not a perfect match

**Comment by fulldecent** [comment]
`git bisect` tells me that this commit is breaking things https://github.com/hybridauth/hybridauth/commit/6176cf0cf7cc47aa0daed4f1ea835523f37e5f39

**Comment by alixandru** [comment]
If you're using the Google login, make sure you have the latest plugin code. The Google provider was updated at some point to use the regular Google Mail login and not the Google Plus login. Depending on you preference you can enable one or the other. Let me know how it goes.

**Comment by fulldecent** [comment]
Thank you, this is fixed in the latest version.
