### ISSUE TITLE
Using q2a-open-login pollutes user table

### ISSUE THREAD

**Issue by fulldecent** [alixandru/q2a-open-login#57]
Registering one account on a Q2A site with q2a-open-login will create multiple rows in the qa_users table

**Comment by alixandru** [comment]
Are you sure there was not an user alreay existing before the registration? One registration through this plugin should render exactly one record in qa_users and exactly one record in qa_user_logins table.

**Comment by fulldecent** [comment]
I am not able to reproduce now, closing.

It is possible this error was related to an out-of-memory situation on this server previously. Just wanted to note in case anyone else is seeing this too.'
