### ISSUE TITLE
Please add VK login

### ISSUE THREAD

**Issue by vyahhi** [alixandru/q2a-open-login#58]
VK.com is the largest social network in Russia and Europe.
Docs: https://vk.com/dev/openapi

**Comment by alixandru** [comment]
I'm afraid you will have to direct your request towards the [HybridAuth project](https://github.com/hybridauth/hybridauth). This plugin uses HybridAuth internally and I have no plans to implement login providers outside of it.

**Comment by vyahhi** [comment]
Thank you for quick response!

**Comment by vyahhi** [comment]
By the way, VK is implemented in HybridAuth –https://github.com/hybridauth/hybridauth/blob/f2623a991e0627a885d79753623354cc17632c7c/additional-providers/hybridauth-vkontakte/Providers/Vkontakte.php.

**Comment by alixandru** [comment]
Oh, then simply drop it in the "providers" directory from the plugin. You should see it instantly in the Q2A Admin page and you can enable it from there. 

Note: I see the current Hybridauth version is different from the one used in the plugin, but I hope the providers are compatible across versions. Let me know if you get any errors.
