### ISSUE TITLE
login box not displaying in cleanstrap theme

### ISSUE THREAD

**Issue by gautamshelley** [alixandru/q2a-open-login#59]

**Comment by alixandru** [comment]
what theme is that? is it standard (shipping with q2a) or a custom theme?

**Comment by gautamshelley** [comment]
standard , based on bootstrap , actually the issue arises coz for register and login the theme uses a modal and in that modal the external sign in  ( fb, g+) box is not displaying .....could u please check this out and guide me how to add it to the modal .......here's the theme http://qa-themes.com/shop/cleanstrap I'll be highly grateful

**Comment by alixandru** [comment]
I'm afraid I cannot help you much with that. You'll need to hack into the
theme's code and insert the login buttons in the right place.

The code for displaying the login buttons from the plugin is found in
qa_open_login.php
(see functions login_html and logout_html). You need to make sure, somehow,
that the HTML code for login buttons is put inside that modal. I cannot
check the theme's code right now, so I don't know exactly where to point
you to.

**Comment by gautamshelley** [comment]
Yp thanku
