### ISSUE TITLE
User details are not receiving from facebook 

### ISSUE THREAD

**Issue by sandyv10** [alixandru/q2a-open-login#60]
Hi Alixandru,

I'm getting an issue with facebook login. When any user login with facebook, we receive User picture & Display name only but not other details like email, name, DOB etc. Currently we are using Q2A facebook login plugin & its working fine. But to add more login providers we need q2a-open-login plugin.
Please help 

Thanks in advance

**Comment by alixandru** [comment]
Yup, looks like Facebook changed a few things in the mean time. Looking into it.

**Comment by reemseat** [comment]
Hello @alixandru. Thanks so much for this plugin, it helps a lot.
Im also having thesame issue here. I get the handle, image but not the email. Its slowed me down for months. Will really appreciate if you can take a look at the plugin. Thanks

**Comment by reemseat** [comment]
I just updated the latest facebook.php from the latest Hybridauth and it fixed the issue. Facebook now reads the email :+1:
