### ISSUE TITLE
Problem with Linkedin

### ISSUE THREAD

**Issue by iPavvel** [alixandru/q2a-open-login#62]
I have a problem with Linkedin connection. I typed app id and secret id in plugin section and callback link in linkedin app page. 
I tried meny times but it's not working.
maybe API is old.

**Comment by alixandru** [comment]
do you get any error in the error log?

**Comment by iPavvel** [comment]
Yes, i have this 

[Tue Jan 19 15:14:56 2016] [warn] [client 83.13.165.193] mod_fcgid: stderr: PHP Notice:  Undefined index:  oauth_token in /home/mywebsite/domains/mywebsite.pl/public_html/qa/qa-plugin/q2a-open-login-master/Hybrid/Providers/LinkedIn.php on line 61

[Tue Jan 19 15:14:56 2016] [warn] [client 83.13.165.193] mod_fcgid: stderr: PHP Notice:  Undefined index:  oauth_verifier in /home/mywebsite/domains/mywebsite.pl/public_html/qa/qa-plugin/q2a-open-login-master/Hybrid/Providers/LinkedIn.php on line 62
