### ISSUE TITLE
Facebook login fails

### ISSUE THREAD

**Issue by gnomezgrave** [alixandru/q2a-open-login#66]
When I try to login with Facebook, it gives me an error after the redirection.

`Fatal error: Call to undefined function qa_open_login_get_new_source() in ~/public_html/project/qa-include/qa-base.php(595) : eval()'d code on line 85`

Any idea why?

Q2A version : 1.7.4

**Comment by alixandru** [comment]
Not sure. Check that you are using the last version from the master branch and not an old version. Other than that, I have no idea.

**Comment by alixandru** [comment]
Closing this for now.
