### ISSUE TITLE
Please update OpenAUTH API calls to Graph API v2.1 or higher

### ISSUE THREAD

**Issue by GeoffAU** [alixandru/q2a-open-login#68]
I have received the following warning from Facebook which may need to be fixed before August:

"OpenAUTH has been making recent API calls to Graph API v2.0, which will reach the end of the 2-year deprecation window on Monday, August 8, 2016. Please migrate all calls to v2.1 or higher in order to avoid potential broken experiences."

**Comment by yshiga** [comment]
I have received this as well

**Comment by alixandru** [comment]
The auth library has just been updated to latest version. Closing this for now.
