### ISSUE TITLE
Can't get email from Facebook login

### ISSUE THREAD

**Issue by vanduc1102** [alixandru/q2a-open-login#69]
Hi, 

Just a notice

I can not get email from facebook login,

But when I replace the folder **Hybrid** with version [V2.6](https://github.com/hybridauth/hybridauth/releases/tag/v2.6.0)

I can get facebook email.

Facebook API version , I used is v2.7

Btw, Thank you so much for a great plugin.

**Comment by JFOC** [comment]
So what you did is only replacing Hybridoauth from [https://github.com/hybridauth/hybridauth/tree/master/hybridauth](https://github.com/hybridauth/hybridauth/tree/master/hybridauth) without any modification ?

**Comment by vanduc1102** [comment]
Yes,
