### ISSUE TITLE
Domain with "www" and without "www"

### ISSUE THREAD

**Issue by vanduc1102** [alixandru/q2a-open-login#71]
I have configured open Auth , it worked well without "www"

But If I started with the URL contains "www", I got the error message

**You cannot access this page directly.**

How can I solve this issue ? thanks

**Comment by alixandru** [comment]
Check app settings în Google Console

**Comment by vanduc1102** [comment]
I add both link with "www" and www to google, but i seems doesnt work correctly,

I will try solution with .htdocs to remove "www" completely

**Comment by poVoq** [comment]
This is still an issue. I tried redirecting all requests to the site via .htaccess without www. but this plugin insists on putting www. everywhere.

It also doesn't play along nicely with a site that is placed under https://mysite.com/q2a/ but with a redirecting causing it to be displayed under https://mysite.com

**Comment by alixandru** [comment]
In Q2A settings, adjust the site URL. The plugin uses it when redirecting.
Also, you should stick to only one variant: with or without www, but not
both at the same time.


On Monday, December 25, 2017, poVoq <notifications@github.com> wrote:
> This is still an issue. I tried redirecting all requests to the site via
.htaccess without www. but this plugin insists on putting www. everywhere.
>
> It also doesn't play along nicely with a site that is placed under
https://mysite.com/q2a/ but with a redirecting causing it to be displayed
under https://mysite.com
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or mute the thread.<
https://ci5.googleusercontent.com/proxy/OXw0y9tCAIJSED0qrjyDSBihfueoFGUKQvFn7QQsjdz7LT1mbBK4y5RmYHX5Hp1ccOC-pGSSIlx6rfJDz779XzOxih8NzV6WiDdiKhme5Zw8r54FLObApbPqPC0v18aMmDLZUe3zB3570yKxIDWzwljNnIElOA=s0-d-e1-ft#https://github.com/notifications/beacon/AAJdtYatutgGYAfgUeKIjLRLvUGYax3Xks5tD2rYgaJpZM4Ju9tz.gif>

**Comment by poVoq** [comment]
Now I feel a bit stupid for having overlooked that  for so long :(
