### ISSUE TITLE
suddenly getting Missing provider application credentials error!?

### ISSUE THREAD

**Issue by Coderx7** [alixandru/q2a-open-login#72]
the plugin was working just fine, untill suddenly one of our users reported he can not login using it anymore, I checked and recieved this error!:
`?hauth.done=Google&code=4/Id6JpI22ry4YZurnH5kTIL6YXHL28Yt40HFI5QklSTo#`
what is causing this? how can I fix it?

**Comment by alixandru** [comment]
The auth library has just been updated to latest version. If this error is still occurring, please comment  here. Closing this for now.
