### ISSUE TITLE
Login as another user

### ISSUE THREAD

**Issue by teju2friends** [alixandru/q2a-open-login#75]
q2a - 1.8, 1.74 & below

When user logs in, some times logs in as different user.
The problem is well discussed here : http://question2answer.org/qa/54400/strange-problem-login-as-another-user

**Comment by alixandru** [comment]
Seems to be related to incorrect error handling. I'll have a look later today.

**Comment by alixandru** [comment]
As stated by other users, this is not related to this plugin, but rather to the hosting company aggressively caching all requests. Closing this.
