### ISSUE TITLE
Can not work with google today

### ISSUE THREAD

**Issue by soliChen** [alixandru/q2a-open-login#76]
It works fine before these days. Q2A  version 1.7.1 ,login plugin v3.0 , had been used for 1+ year.
When I login with google into Q2A today, after clicking "Allow" from google permission , HTTP ERROR 500 came.
I tried to build a new Q2A and set this login plugin, and got the same error , after clicking "Allow".
I tried to update this plugin with newest Hybrid folder from its' official website and tried again.It didn't work (still after clicking "Allow") .
What can I do to fix this problem?

**Comment by solidChen** [comment]
I solved this issue by myself today.
Just updated the newest "Hybrid" folder and everything work fine again.
download that from "Hybridauth" project: https://github.com/hybridauth/hybridauth
Firstly,delete the "Hybrid" folder from this q2a-open-login plugin's folder. And then, copy the "Hybrid" folder from upper project "Hybridauth" into this q2a-open-login 's folder.
Google login work again.

**Comment by Hitman666** [comment]
Thank you, this just solved the same issue I ran into!

**Comment by alixandru** [comment]
The auth library has just been updated to latest version. Closing this for now.
