### ISSUE TITLE
merge action can not be confirmed with some themes

### ISSUE THREAD

**Issue by poVoq** [alixandru/q2a-open-login#78]
Using the nice donut theme the button to "continue" with merging two accounts is not rendered and thus the function can not be used. When I switch to the classic theme it works.

**Comment by Schoaf** [comment]
I can confirm that. @poVoq do you have any workaround?

**Comment by Schoaf** [comment]
The button has the style display: none and thus is not being displayed.
I didn't get the script working properly to update the button so the quickfix for me is to set "display:block" on button definition (line 510 in qa-open-page-logins.php)

**Comment by alixandru** [comment]
Unfortunately it is not feasible to have a CSS stylesheet file for each and every theme, so any adjustments would need to be made on the spot. I'll close this for now, since there was already a workaround provided above. Thanks!
